all:
  children:
    controlplane:
      hosts:
        controleplane:
          ansible_host: 192.168.50.10
          ansible_user: root

    workers:
      hosts:
        worker:
          ansible_host: 192.168.50.20
          ansible_user: root

    k8s:
      children:
        controlplane:
        workers:
