- name: Installation commune KUBEADM sur Control Plane et Worker
  hosts: k8s
  become: true
  tasks:
    - name: Desactiver le SWAP
      command: swapoff -a
      changed_when: false

    - name: Desactiver le swap dans fstab
      replace:
        path: /etc/fstab
        regexp: '^\s*([^#\n]+\s+){1}swap\s+'
        replace: '# \g<0>'

    - name: Installer les paquets necessaires
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - apt-transport-https
        state: present
        update_cache: true

    - name: Charger les modules du kernel
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: S'assurer du bon chargement des modules du kernel
      shell: |
        modprobe overlay
        modprobe br_netfilter
      args:
        executable: /bin/bash

    - name: Configuration du routage interne
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: Application du routage interne
      command: sysctl --system
      changed_when: false

    - name: Installation de containerd
      apt:
        name: containerd
        state: present
        update_cache: true

    - name: Creation d'un fichier de configuration containerd
      shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
      args:
        executable: /bin/bash
      changed_when: false

    - name: Activer Systemd comme Cgroup
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Acitvation de containerd
      systemd:
        name: containerd
        enabled: true
        state: restarted

    - name: Ajout de la cle GPG de KUBEADM
      shell: |
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        executable: /bin/bash
      changed_when: false

    - name: Ajout du repos KUBEADM
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /

    - name: Installation de kubelet kubeadm kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: true

    - name: Empechement des MAJ de kubelet kubeadm kubectl
      shell: |
        apt-mark hold kubelet kubeadm kubectl
      args:
        executable: /bin/bash
      changed_when: false
